# Generated by Django 5.1.1 on 2025-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
