# Generated by Django 5.1.4 on 2025-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_track_playlist_follower_count_playlist_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='session_id',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
